name: performance

on:
    push:
        branches:
            - "**main**"
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [ubuntu-22.04]

            fail-fast: false

        steps:
            - uses: actions/checkout@v1
              with:
                  fetch-depth: 1

            - name: dependency (ubuntu)
              run: |
                  sudo apt-get -qy install python3 python3-pip
                  python3 -m pip install -r requirements.txt

            - name: performance
              run: |
                  make performance
